const keys = {
  en: [
    {
      key: '`',
      keyCode: 192,
      which: 192,
      code: 'Backquote',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '~',
    },
    {
      key: '1',
      keyCode: 49,
      which: 49,
      code: 'Digit1',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '!',
    },
    {
      key: '2',
      keyCode: 50,
      which: 50,
      code: 'Digit2',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '@',
    },
    {
      key: '3',
      keyCode: 51,
      which: 51,
      code: 'Digit3',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '#',
    },
    {
      key: '4',
      keyCode: 52,
      which: 52,
      code: 'Digit4',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '$',
    },
    {
      key: '5',
      keyCode: 53,
      which: 53,
      code: 'Digit5',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '%',
    },
    {
      key: '6',
      keyCode: 54,
      which: 54,
      code: 'Digit6',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '^',
    },
    {
      key: '7',
      keyCode: 55,
      which: 55,
      code: 'Digit7',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '&',
    },
    {
      key: '8',
      keyCode: 56,
      which: 56,
      code: 'Digit8',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '*',
    },
    {
      key: '9',
      keyCode: 57,
      which: 57,
      code: 'Digit9',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '(',
    },
    {
      key: '0',
      keyCode: 48,
      which: 48,
      code: 'Digit0',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: ')',
    },
    {
      key: '-',
      keyCode: 189,
      which: 189,
      code: 'Minus',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '_',
    },
    {
      key: '=',
      keyCode: 187,
      which: 187,
      code: 'Equal',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '+',
    },
    {
      key: 'Backspace',
      keyCode: 8,
      which: 8,
      code: 'Backspace',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_back',
      changeText: true,
      text: 'BACKSPACE',
    },
    {
      key: 'Home',
      keyCode: 36,
      which: 36,
      code: 'Home',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_grey',
      changeText: true,
      text: 'Home',
    },
    {
      key: 'Tab',
      keyCode: 9,
      which: 9,
      code: 'Tab',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_tab',
      changeText: true,
      text: 'TAB',
    },
    {
      key: 'q',
      keyCode: 81,
      which: 81,
      code: 'KeyQ',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'w',
      keyCode: 87,
      which: 87,
      code: 'KeyW',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'e',
      keyCode: 69,
      which: 69,
      code: 'KeyE',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'r',
      keyCode: 82,
      which: 82,
      code: 'KeyR',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 't',
      keyCode: 84,
      which: 84,
      code: 'KeyT',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'y',
      keyCode: 89,
      which: 89,
      code: 'KeyY',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'u',
      keyCode: 85,
      which: 85,
      code: 'KeyU',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'i',
      keyCode: 73,
      which: 73,
      code: 'KeyI',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'o',
      keyCode: 79,
      which: 79,
      code: 'KeyO',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'p',
      keyCode: 80,
      which: 80,
      code: 'KeyP',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: '[',
      keyCode: 219,
      which: 219,
      code: 'BracketLeft',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '{',
    },
    {
      key: ']',
      keyCode: 221,
      which: 221,
      code: 'BracketRight',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '}',
    },
    {
      key: '\\',
      keyCode: 220,
      which: 220,
      code: 'Backslash',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_tab',
      shiftMode: '|',
    },
    {
      key: 'End',
      keyCode: 35,
      which: 35,
      code: 'Numpad1',
      location: 3,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_grey',
      changeText: true,
      text: 'End',
    },
    {
      key: 'CapsLock',
      keyCode: 20,
      which: 20,
      code: 'CapsLock',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_caps',
      changeText: true,
      text: 'CAPS LOCK',
    },
    {
      key: 'a',
      keyCode: 65,
      which: 65,
      code: 'KeyA',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 's',
      keyCode: 83,
      which: 83,
      code: 'KeyS',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'd',
      keyCode: 68,
      which: 68,
      code: 'KeyD',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'f',
      keyCode: 70,
      which: 70,
      code: 'KeyF',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'g',
      keyCode: 71,
      which: 71,
      code: 'KeyG',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'h',
      keyCode: 72,
      which: 72,
      code: 'KeyH',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'j',
      keyCode: 74,
      which: 74,
      code: 'KeyJ',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'k',
      keyCode: 75,
      which: 75,
      code: 'KeyK',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'l',
      keyCode: 76,
      which: 76,
      code: 'KeyL',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: ';',
      keyCode: 186,
      which: 186,
      code: 'Semicolon',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: ':',
    },
    {
      key: ';',
      keyCode: 186,
      which: 186,
      code: 'Semicolon',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '"',
    },
    {
      key: 'Enter',
      keyCode: 13,
      which: 13,
      code: 'Enter',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_enter',
      changeText: true,
      text: 'ENTER',
    },
    {
      key: 'Insert',
      keyCode: 45,
      which: 45,
      code: 'Insert',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_grey',
      changeText: true,
      text: 'Insert',
    },
    {
      key: 'Shift',
      keyCode: 16,
      which: 16,
      code: 'ShiftLeft',
      location: 1,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: true,
      repeat: false,
      class: 'keyboard__button keyboard__button_lshift',
      changeText: true,
      text: 'SHIFT',
    },
    {
      key: 'z',
      keyCode: 90,
      which: 90,
      code: 'KeyZ',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'x',
      keyCode: 88,
      which: 88,
      code: 'KeyX',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'c',
      keyCode: 67,
      which: 67,
      code: 'KeyC',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'v',
      keyCode: 86,
      which: 86,
      code: 'KeyV',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'b',
      keyCode: 66,
      which: 66,
      code: 'KeyB',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'n',
      keyCode: 78,
      which: 78,
      code: 'KeyN',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'm',
      keyCode: 77,
      which: 77,
      code: 'KeyM',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: ',',
      keyCode: 188,
      which: 188,
      code: 'Comma',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '<',
    },
    {
      key: '.',
      keyCode: 190,
      which: 190,
      code: 'Period',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '>',
    },
    {
      key: '/',
      keyCode: 191,
      which: 191,
      code: 'Slash',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '?',
    },
    {
      key: 'Shift',
      keyCode: 16,
      which: 16,
      code: 'ShiftRight',
      location: 2,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: true,
      repeat: false,
      class: 'keyboard__button keyboard__button_caps',
      changeText: true,
      text: 'SHIFT',
    },
    {
      key: 'ArrowUp',
      keyCode: 38,
      which: 38,
      code: 'ArrowUp',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_arrup',
      changeText: true,
      text: '⟶',
    },
    {
      key: 'Delete',
      keyCode: 46,
      which: 46,
      code: 'Delete',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_grey',
      changeText: true,
      text: 'Del',
    },
    {
      key: 'Control',
      keyCode: 17,
      which: 17,
      code: 'ControlLeft',
      location: 1,
      altKey: false,
      ctrlKey: true,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_lctrl',
      changeText: true,
      text: 'CTRL',
    },
    {
      key: 'Meta',
      keyCode: 91,
      which: 91,
      code: 'MetaLeft',
      location: 1,
      altKey: false,
      ctrlKey: false,
      metaKey: true,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_win',
      changeText: true,
      text: 'WIN',
    },
    {
      key: 'Alt',
      keyCode: 18,
      which: 18,
      code: 'AltLeft',
      location: 1,
      altKey: true,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_ralt',
      changeText: true,
      text: 'ALT',
    },
    {
      key: ' ',
      keyCode: 32,
      which: 32,
      code: 'Space',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_space',
    },
    {
      key: 'Alt',
      keyCode: 18,
      which: 18,
      code: 'AltRight',
      location: 2,
      altKey: true,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_ralt',
      changeText: true,
      text: 'ALT',
    },
    {
      key: 'Meta',
      keyCode: 91,
      which: 91,
      code: 'MetaLeft',
      location: 1,
      altKey: false,
      ctrlKey: false,
      metaKey: true,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_rwin',
      changeText: true,
      text: 'WIN',
    },
    {
      key: 'Control',
      keyCode: 17,
      which: 17,
      code: 'ControlRight',
      location: 2,
      altKey: false,
      ctrlKey: true,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_rctrl',
      changeText: true,
      text: 'CTRL',
    },
    {
      key: 'ArrowLeft',
      keyCode: 37,
      which: 37,
      code: 'ArrowLeft',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_left',
      changeText: true,
      text: '⟵',
    },
    {
      key: 'ArrowDown',
      keyCode: 40,
      which: 40,
      code: 'ArrowDown',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_down',
      changeText: true,
      text: '⟶',
    },
    {
      key: 'ArrowRight',
      keyCode: 39,
      which: 39,
      code: 'ArrowRight',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_right',
      changeText: true,
      text: '⟶',
    },
  ],
  ru: [
    {
      key: 'ё',
      keyCode: 192,
      which: 192,
      code: 'Backquote',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: '1',
      keyCode: 49,
      which: 49,
      code: 'Digit1',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '!',
    },
    {
      key: '2',
      keyCode: 50,
      which: 50,
      code: 'Digit2',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '"',
    },
    {
      key: '3',
      keyCode: 51,
      which: 51,
      code: 'Digit3',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '№',
    },
    {
      key: '4',
      keyCode: 52,
      which: 52,
      code: 'Digit4',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: ';',
    },
    {
      key: '5',
      keyCode: 53,
      which: 53,
      code: 'Digit5',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: '6',
      keyCode: 54,
      which: 54,
      code: 'Digit6',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: ':',
    },
    {
      key: '7',
      keyCode: 55,
      which: 55,
      code: 'Digit7',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '?',
    },
    {
      key: '8',
      keyCode: 56,
      which: 56,
      code: 'Digit8',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '*',
    },
    {
      key: '9',
      keyCode: 57,
      which: 57,
      code: 'Digit9',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '(',
    },
    {
      key: '0',
      keyCode: 48,
      which: 48,
      code: 'Digit0',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: ')',
    },
    {
      key: '-',
      keyCode: 189,
      which: 189,
      code: 'Minus',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '_',
    },
    {
      key: '=',
      keyCode: 187,
      which: 187,
      code: 'Equal',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: '+',
    },
    {
      key: 'Backspace',
      keyCode: 8,
      which: 8,
      code: 'Backspace',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_back',
      changeText: true,
      text: 'BACKSPACE',
    },
    {
      key: 'Home',
      keyCode: 36,
      which: 36,
      code: 'Home',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_grey',
      changeText: true,
      text: 'Home',
    },
    {
      key: 'Tab',
      keyCode: 9,
      which: 9,
      code: 'Tab',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_tab',
      changeText: true,
      text: 'TAB',
    },
    {
      key: 'й',
      keyCode: 81,
      which: 81,
      code: 'KeyQ',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'ц',
      keyCode: 87,
      which: 87,
      code: 'KeyW',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'у',
      keyCode: 69,
      which: 69,
      code: 'KeyE',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'к',
      keyCode: 82,
      which: 82,
      code: 'KeyR',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'е',
      keyCode: 84,
      which: 84,
      code: 'KeyT',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'н',
      keyCode: 89,
      which: 89,
      code: 'KeyY',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'г',
      keyCode: 85,
      which: 85,
      code: 'KeyU',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'ш',
      keyCode: 73,
      which: 73,
      code: 'KeyI',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'щ',
      keyCode: 79,
      which: 79,
      code: 'KeyO',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'з',
      keyCode: 80,
      which: 80,
      code: 'KeyP',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'х',
      keyCode: 219,
      which: 219,
      code: 'BracketLeft',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'ъ',
      keyCode: 221,
      which: 221,
      code: 'BracketRight',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: '\\',
      keyCode: 220,
      which: 220,
      code: 'Backslash',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_tab',
    },
    {
      key: 'End',
      keyCode: 35,
      which: 35,
      code: 'Numpad1',
      location: 3,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_grey',
      changeText: true,
      text: 'End',
    },
    {
      key: 'CapsLock',
      keyCode: 20,
      which: 20,
      code: 'CapsLock',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_caps',
      changeText: true,
      text: 'CAPS LOCK',
    },
    {
      key: 'ф',
      keyCode: 65,
      which: 65,
      code: 'KeyA',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'ы',
      keyCode: 83,
      which: 83,
      code: 'KeyS',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'в',
      keyCode: 68,
      which: 68,
      code: 'KeyD',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'а',
      keyCode: 70,
      which: 70,
      code: 'KeyF',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'п',
      keyCode: 71,
      which: 71,
      code: 'KeyG',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'р',
      keyCode: 72,
      which: 72,
      code: 'KeyH',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'о',
      keyCode: 74,
      which: 74,
      code: 'KeyJ',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'л',
      keyCode: 75,
      which: 75,
      code: 'KeyK',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'д',
      keyCode: 76,
      which: 76,
      code: 'KeyL',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'ж',
      keyCode: 186,
      which: 186,
      code: 'Semicolon',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'э',
      keyCode: 186,
      which: 186,
      code: 'Semicolon',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'Enter',
      keyCode: 13,
      which: 13,
      code: 'Enter',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_enter',
      changeText: true,
      text: 'ENTER',
    },
    {
      key: 'Insert',
      keyCode: 45,
      which: 45,
      code: 'Insert',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_grey',
      changeText: true,
      text: 'Insert',
    },
    {
      key: 'Shift',
      keyCode: 16,
      which: 16,
      code: 'ShiftLeft',
      location: 1,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: true,
      repeat: false,
      class: 'keyboard__button keyboard__button_lshift',
      changeText: true,
      text: 'SHIFT',
    },
    {
      key: 'я',
      keyCode: 90,
      which: 90,
      code: 'KeyZ',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'ч',
      keyCode: 88,
      which: 88,
      code: 'KeyX',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'с',
      keyCode: 67,
      which: 67,
      code: 'KeyC',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'м',
      keyCode: 86,
      which: 86,
      code: 'KeyV',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'и',
      keyCode: 66,
      which: 66,
      code: 'KeyB',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'т',
      keyCode: 78,
      which: 78,
      code: 'KeyN',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'ь',
      keyCode: 77,
      which: 77,
      code: 'KeyM',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'б',
      keyCode: 188,
      which: 188,
      code: 'Comma',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: 'ю',
      keyCode: 190,
      which: 190,
      code: 'Period',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
    },
    {
      key: '.',
      keyCode: 191,
      which: 191,
      code: 'Slash',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button',
      shiftMode: ',',
    },
    {
      key: 'Shift',
      keyCode: 16,
      which: 16,
      code: 'ShiftRight',
      location: 2,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: true,
      repeat: false,
      class: 'keyboard__button keyboard__button_caps',
      changeText: true,
      text: 'SHIFT',
    },
    {
      key: 'ArrowUp',
      keyCode: 38,
      which: 38,
      code: 'ArrowUp',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_arrup',
      changeText: true,
      text: '⟶',
    },
    {
      key: 'Delete',
      keyCode: 46,
      which: 46,
      code: 'Delete',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_grey',
      changeText: true,
      text: 'Del',
    },
    {
      key: 'Control',
      keyCode: 17,
      which: 17,
      code: 'ControlLeft',
      location: 1,
      altKey: false,
      ctrlKey: true,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_lctrl',
      changeText: true,
      text: 'CTRL',
    },
    {
      key: 'Meta',
      keyCode: 91,
      which: 91,
      code: 'MetaLeft',
      location: 1,
      altKey: false,
      ctrlKey: false,
      metaKey: true,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_win',
      changeText: true,
      text: 'WIN',
    },
    {
      key: 'Alt',
      keyCode: 18,
      which: 18,
      code: 'AltLeft',
      location: 1,
      altKey: true,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_ralt',
      changeText: true,
      text: 'ALT',
    },
    {
      key: ' ',
      keyCode: 32,
      which: 32,
      code: 'Space',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_space',
    },
    {
      key: 'Alt',
      keyCode: 18,
      which: 18,
      code: 'AltRight',
      location: 2,
      altKey: true,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_ralt',
      changeText: true,
      text: 'ALT',
    },
    {
      key: 'Meta',
      keyCode: 91,
      which: 91,
      code: 'MetaLeft',
      location: 1,
      altKey: false,
      ctrlKey: false,
      metaKey: true,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_rwin',
      changeText: true,
      text: 'WIN',
    },
    {
      key: 'Control',
      keyCode: 17,
      which: 17,
      code: 'ControlRight',
      location: 2,
      altKey: false,
      ctrlKey: true,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_rctrl',
      changeText: true,
      text: 'CTRL',
    },
    {
      key: 'ArrowLeft',
      keyCode: 37,
      which: 37,
      code: 'ArrowLeft',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_left',
      changeText: true,
      text: '⟵',
    },
    {
      key: 'ArrowDown',
      keyCode: 40,
      which: 40,
      code: 'ArrowDown',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_down',
      changeText: true,
      text: '⟶',
    },
    {
      key: 'ArrowRight',
      keyCode: 39,
      which: 39,
      code: 'ArrowRight',
      location: 0,
      altKey: false,
      ctrlKey: false,
      metaKey: false,
      shiftKey: false,
      repeat: false,
      class: 'keyboard__button keyboard__button_right',
      changeText: true,
      text: '⟶',
    },
  ],
};

export default keys;
